language: python

python:
  - "2.7"
  - "3.4"
  - "3.5"
  - "pypy"

sudo: false

cache:
  - apt
  - pip

services:
  - mongodb

env:
  - REQUIREMENTS=lowest
  - REQUIREMENTS=release

before_install:
  - "travis_retry pip install --upgrade pip setuptools"
  - "travis_retry pip install twine wheel coveralls requirements-builder"
  - "requirements-builder -e all --level=min setup.py > .travis-lowest-requirements.txt"
  - "requirements-builder -e all --level=pypi setup.py > .travis-release-requirements.txt"
  - |
      if [ "$TRAVIS_PYTHON_VERSION" = "pypy" ]; then
        export PYENV_ROOT="$HOME/.pyenv"
        if [ -f "$PYENV_ROOT/bin/pyenv" ]; then
          cd "$PYENV_ROOT" && git pull
        else
          rm -rf "$PYENV_ROOT" && git clone --depth 1 https://github.com/yyuu/pyenv.git "$PYENV_ROOT"
        fi
        export PYPY_VERSION="4.0.1"
        "$PYENV_ROOT/bin/pyenv" install "pypy-$PYPY_VERSION"
        virtualenv --python="$PYENV_ROOT/versions/pypy-$PYPY_VERSION/bin/python" "$HOME/virtualenvs/pypy-$PYPY_VERSION"
        source "$HOME/virtualenvs/pypy-$PYPY_VERSION/bin/activate"
      fi

install:
  - "pip install -r .travis-${REQUIREMENTS}-requirements.txt"
  - "pip install -e .[all]"

script: python setup.py test

after_script:
  - coveralls
