[pytest]
addopts = -xrs --cov flask_security --cov-report term-missing --pep8 --flakes --cache-clear

pep8maxlinelength = 99

pep8ignore =
    docs/* ALL
    scripts/* ALL

flakes-ignore =
    ImportStarUsed
    flask_security/__init__.py UnusedImport
    docs/* ALL
    scripts/* ALL
